apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
    - name: demo-container
      image: yg18/website
      ports:
    - containerPort: 3000
      name: "http"
  env:
    - name: NAME
      value: "Yash"
  restartPolicy: OnFailure
